### ISSUE TITLE
Travis failed timer_event_called at least once randomly, on OSX

### ISSUE THREAD

**Issue by jimklimov** [zeromq/czmq#1754] opened 2017-09-04 20:15 UTC
````
Assertion failed: (timer_event_called), function zloop_test, file ../../src/zloop.c, line 972.
````

**Comment by bluca** [comment] 2017-09-04 20:34
Would need to reproduce in GDB, it's strange since it should loop until the timer expires

**Comment by jimklimov** [comment] 2017-09-04 21:37
There were several hits tonight, all on MacOS so far. One in CMake and one in default build.... e.g.:

https://travis-ci.org/zeromq/czmq/jobs/271793068
https://travis-ci.org/zeromq/czmq/jobs/271793084

**Comment by bluca** [comment] 2017-09-04 21:43
Triggered an older build from a previous commits and it fails in the same way:

https://travis-ci.org/zeromq/czmq/jobs/266767359

Which means it's either a dependency or the environment

**Comment by jimklimov** [comment] 2017-09-05 11:45
May be.... either way, it at least seems broken for new-system users, and also the Travis tests end up red.
Ideally there should be a way to test, at least "manually", that an eventually fixed solution still works on older supported systems as well ;)

**Comment by bluca** [comment] 2017-09-05 14:06
It's the problem of reproducible builds... good news is there is a lot of work going on in distros to make it happen, bad news is it's unlikely that Travis will support that anytime soon
The full environment needs to be recorded together with the result

**Comment by jimklimov** [comment] 2017-09-17 14:51
Bump: this strikes again in recent builds ;)

**Comment by bluca** [comment] 2017-09-17 14:59
There's a few that now fail - including the zeromq 2.x on Linux. It's extraordinarily weird as it started happening at some point in the past couple of weeks, but reverting the code to before that doesn't help. It also doesn't help trying to use older Travis build environments.

And of course I can't reproduce locally. Sigh.

**Comment by AntonBarwald** [comment] 2017-11-02 09:14
I think this has something to do with libzmq, because running older versions of libzmq (4.2.2) works.   

Sometimes on OSX we get ETIMEDOUT instead of EAGAIN. I have send a PR to libzmq: https://github.com/zeromq/libzmq/pull/2742

**Comment by bluca** [comment] 2017-11-02 23:53
Fixed by https://github.com/zeromq/libzmq/pull/2813 thanks @AntonBarwald

**Closed by bluca** 2017-11-02 23:53 UTC
