### ISSUE TITLE
czmq v4.2.1 causes illegal hardware instruction on macos

### ISSUE THREAD

**Issue by yepei14** [zeromq/czmq#2176] opened 2021-04-22 11:04 UTC
Hi,

I tried to use czmq v4.2.1 on my macbook(Big Sur, Apple clang version 12.0.0), but it causes "illegal hardware instruction".

I look into the source code and find line 339 of zsys.c is to blame. It passes ```s_thread_name_prefix_str``` into ```zsys_set_thread_name_prefix_str```, in which ```strcpy(s_thread_name_prefix_str, s_thread_name_prefix_str)``` happens. 

This is part of my lldb output:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x00007fff203fa11f libsystem_c.dylib`__chk_fail_overlap + 16
libsystem_c.dylib`__chk_fail_overlap:
->  0x7fff203fa11f <+16>: ud2    

libsystem_c.dylib`__chk_overlap:
    0x7fff203fa121 <+0>:  pushq  %rbp
    0x7fff203fa122 <+1>:  movq   %rsp, %rbp
    0x7fff203fa125 <+4>:  testq  %rsi, %rsi
Target 2: (rpcclient) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
  * frame #0: 0x00007fff203fa11f libsystem_c.dylib`__chk_fail_overlap + 16
    frame #1: 0x00007fff203fa143 libsystem_c.dylib`__chk_overlap + 34
    frame #2: 0x00007fff203fa2e1 libsystem_c.dylib`__strcpy_chk + 64
    frame #3: 0x000000010016d9aa libvsdk.0.dylib`zsys_set_thread_name_prefix_str + 106
    frame #4: 0x000000010016cfb3 libvsdk.0.dylib`zsys_init + 1971
    frame #5: 0x000000010016db39 libvsdk.0.dylib`zsys_socket + 25
    frame #6: 0x0000000100166b53 libvsdk.0.dylib`zsock_new_checked + 67
    frame #7: 0x000000010016dca8 libvsdk.0.dylib`zsys_create_pipe + 56
    frame #8: 0x0000000100145a65 libvsdk.0.dylib`zactor_new + 101
```

**Comment by bluca** [comment] 2021-04-22 11:11
duplicate of https://github.com/zeromq/czmq/issues/2161

**Closed by bluca** 2021-04-22 11:11 UTC
