### ISSUE TITLE
CZMQ version: 3.0.3

### ISSUE THREAD

**Issue by jawadatgithub** [zeromq/czmq#1654] opened 2017-03-28 15:56 UTC
On July 18, 2016, I downloaded czmq master and build it, the version at runtime reported as:
CZMQ version: 3.0.3
and in project.xml:
    `<version major = "3" minor = "0" patch = "3" />`

but when i check for releases, v3.0.3 doesn't exist, instead the project jumped from 3.0.2 to 4.0.0 Release Candidate 1! Nov 1, 2016, so how i can track the changes between Nov 1, 2016 and July 18, 2016?

**Comment by jawadatgithub** [comment] 2017-03-28 16:27
I found the following commit on Nov 1, 2016:

https://github.com/zeromq/czmq/commit/d30c19d3baf2f9a685c3f67a942cd4fe793c76c3
Problem: many API/ABI breakages for a patch version bump  …
Solution: bump version to 4.0.0 from 3.0.3. Incidentally ABI
also will be 4.0.0 so that's convenient.

**that's not cool**, it seems I have to download new release, and make a lot of testing and code changes to stay up to date! but the most annoying thing is that current release CZMQ 4.0.2 is not up to date with latest release libzmq 4.2.2!

how long ZeroMQ will keep its users busy tracking the race between the libs?

I am pointing this, since I discovered networking issue with the 3.0.3, and by checking the latest commits in libzmq its being fixed, and in my case I am using czmq on CentOS as Client and clrzmq4 on Windows as server, so the point mentioned in the docs about the great compatibility between releases seems FALSE!

**Comment by bluca** [comment] 2017-03-28 16:46
When a release is cut, on the master branch the version numbers are immediately incremented, to differentiate from the release versions and avoid confusing binaries.

So when 3.0.2 was released, it was incremented to 3.0.3. This is normal, and as you can see the latest release is 4.0.2 but on the master branch it's set to 4.0.3 already: https://github.com/zeromq/czmq/blob/master/project.xml#L11

During the development cycle it was later further bumped to 4.0 since it was time to retire APIs that had been declared deprecated 2 years earlier.

If you don't wish to use an unreleased version, then the tagged released are there for that reason:

https://github.com/zeromq/czmq/releases

You can check all the changes between 3.0.2 and 4.0.0 in the release page for the changelog:

https://github.com/zeromq/czmq/releases/tag/v4.0.0

And github allows even to see each individual commit, if you are interested in that kind of detail:

https://github.com/zeromq/czmq/compare/v3.0.2...v4.0.0

You can do the same easily with a local clone.

> that's not cool, it seems I have to download new release, and make a lot of testing and code changes to stay up to date! but the most annoying thing is that current release CZMQ 4.0.2 is not up to date with latest release libzmq 4.2.2!

Not sure what do you mean, CZMQ 4.0.2 works just fine with libzmq 4.2 (and 4.1 and 4.0 and down to 2.x)

> how long ZeroMQ will keep its users busy tracking the race between the libs?

Not sure what you mean here either, there is no race, you can mix and match pretty liberally in general if that's what you wish to do.
With the next version of CZMQ you'll even be able to compile CZMQ against a version of libzmq and then use a different one at runtime (with some limits), so that's even more flexibility

> I am pointing this, since I discovered networking issue with the 3.0.3, and by checking the latest commits in libzmq its being fixed, and in my case I am using czmq on CentOS as Client and clrzmq4 on Windows as server, so the point mentioned in the docs about the great compatibility between releases seems FALSE!

Not sure what you mean here too, you can use CZMQ 3.x with any version of libzmq since 2.x, and the same goes for newer versions too

**Comment by jawadatgithub** [comment] 2017-03-28 17:15
Yes! everything work with everything, but when it comes to figure out which lib causing performance issues its a nightmare! my networking issue related to SO_SNDBUF and SO_RCVBUF, check below issue:

https://github.com/zeromq/libzmq/issues/1947

clrzmq release usually comes with pre built libzmq, so to resolve the socket buffering issue that's being resolved in recent libzmq, alot of changes will be required.

anyway, thanks!

**Comment by bluca** [comment] 2017-03-28 17:37
When there's a regression and a simple way to reproduce it, as demonstrated in the issue you linked, it's not very hard to git bisect and find out where the origin is, just takes some time and dedication.
Anyway it's not in any way related to version numbers or releases, a regression can happen at any point in time anywhere, it's really not different from any other software project anywhere.
Given there's nothing to be done here, closing now.

**Closed by bluca** 2017-03-28 17:37 UTC
