### ISSUE TITLE
zsock_send() va_arg incorrect type - potential segfault

### ISSUE THREAD

**Issue by g8trbryant** [zeromq/czmq#982] opened 2015-04-01 16:42 UTC
Possible segfault: due to wrong type causing extreme-sized buffer creation.

I ran into an intermittent issue after accidentally providing an int for the size value instead of size_t in the 'b'-picture for the zsock_send.  It only manifests on rare occasions and small unrelated code changes can change the result.  Through gdb I determined that a buffer was being created and on some specific circumstances the 64-bit size_t being used by the function had extra data in the upper 32-bits (note: the int I provided was in the lower 32-bits).

After debugging my issue and figuring out that I needed a size_t instead, I noticed that the same error is occurring internally. Unfortunately due to the intermittent nature of this, I have not tested if this can cause an error by itself (with the user providing a size_t).  However, it should still probably be changed

//zsock.c:684
if (*picture == 'b') {
            //  Note function arguments may be expanded in reverse order,
            //  so we cannot use va_arg macro twice in a single call
            byte *data = va_arg (argptr, byte *);
            zmsg_addmem (msg, data, va_arg (argptr, **int**));
        }

zmsg_addmem (zmsg_t *self, const void *src, **size_t** size)

**Comment by twhittock** [comment] 2015-05-07 20:33
the 'b' picture is documented as taking an `int`. `va_arg` interptets the incoming data as an int. the compiler then takes that int value and implicitly casts it to `size_t`. This should all work fine. What platform is this on? What size is `int` on this platform? What specific circumstances let do the upper bits being set? Did the bits relate to any other data being passed, eg the pointer?

**Comment by bluca** [comment] 2017-01-01 14:20
Closing since there was no answer in more than a year and this problem hasn't been observed since. Please reopen if this can be still reproduced.

**Closed by bluca** 2017-01-01 14:20 UTC
