### ISSUE TITLE
zmq_getsockopt for ZMQ_FD fails

### ISSUE THREAD

**Issue by HAlakeshwar** [zeromq/czmq#893] opened 2015-01-14 12:49 UTC
I have downloaded the 3.0.0-rc1 release of CZMQ. I am trying to write a prototype that uses the zbeacon protocol for service discovery on windows x64 machine. When I run czmq_selftest I get fails in  zsock_test, zpoller_test and zbeacon_test. I tested CZMQ using both vs2012 and vs2013 build versions. 

zsock_test: On debugging the zsock_test, I find that zsock_fd(reader) at line 939 on zsock.c returns an invalid fd. Digging deeper it looks like zmq_getsockopt fails to return the pointer to the file descriptor socket at line 1585 of zsock.c. 

zpoller_test: Assertion comparing the return of zpoller_wait and the file descriptor fails because the zpoller_wait returns a 0 value where as in the earlier call zsock_Fd returns an un initialized fd. I believe this is again an issue with zsock_fd.

zbeacon_test: The problem here seems to be in sending a byte\* in zsock_send. 

Thanks for looking into this. 
Harsha

**Comment by hintjens** [comment] 2015-01-14 16:40
Ok, thanks for reporting these. Can you confirm that CZMQ master has the
same issues? Then we'll fix them one by one.

Also can you provide line numbers for any assertion failures, and a stack
dump if possible, thanks.

**Comment by HAlakeshwar** [comment] 2015-01-15 14:38
I have just run the CZMQ master and the CMZQ_tests fail at
* zchunk: OK
* zconfig: OK
* zclock: Assertion failed: (zclock_usecs () - usecs) >= 10000, file ..\..\..\..\src\zclock.c, line 225
//
commenting zclock and running ahead I get.
 * ziflist: OK
 * zuuid: OK
 * zsock: Assertion failed: zsock_resolve ((void *) &fd) == NULL, file ..\..\..\..\src\zsock.c, line 1458
You can find the dump for the zsock here. 
[czmq_selftest.zipx | uploaded via ZenHub](https://files.zenhub.io/54b7d0d1a249c8781446d0a0)

**Comment by HAlakeshwar** [comment] 2015-01-15 14:46
I also found issues with zpoller. The dump file for it is attached below
[czmq_selftest_zpoller.zipx | uploaded via ZenHub](https://files.zenhub.io/54b7d289a249c8781446d0d3)

Everything else including zbeacon runs fine on the main branch.

Thanks for checking and coming back to me quickly.

Cheers,
Harsha

**Comment by hintjens** [comment] 2015-01-16 13:45
OK, can you please file one issue per problem? Since you have the
compiler/OS that reproduces the problems, the most helpful thing would be
pull requests with fixes :-) (I don't have Windows so otherwise we'll wait
for someone with that mix to help here.)

**Comment by bluca** [comment] 2017-01-01 13:25
Closing as this was fixed as part of #898 and #899

**Closed by bluca** 2017-01-01 13:25 UTC
